theme: jekyll-theme-hacker

title: "DB Relacionales | Bases de Datos Relacionales | UCALDAS"
description: "Portafolio y biblioteca de estudio para el manejo de Bases de Datos Relacionales. Contiene desde fundamentos teóricos hasta la aplicación práctica de conceptos avanzados como integraciones con bases de datos en la nube (ej. Neon) y extensiones para búsquedas vectoriales (pgvector)."
author: tutosrive

google_analytics: "G-JNLZF5SXSP"

icon: "👩🏻‍💻"
image: "https://cdn.jsdelivr.net/gh/tutosrive/images-projects-srm-trg@main/others/sql1.png"
